language: node_js
node_js:
    - '6'
sudo: false
install:
    - npm install
script:
    - npm run build
before_deploy:
    - shopt -s extglob
    - GLOBIGNORE='.git'
    - rm -rf !(.nojekyll|LICENSE|README.md|_book)
    - cp -r _book/* .
    - rm -rf _book
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
notifications:
    email: false
